name: linting, testing, building
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
          - '17.x'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install modules
        run: npm install
      - name: Linting
        run: npm run lint:ts && npm run lint:scss
      - name: Build production project
        run: npm run build:prod
      - name: Run unit tests
        run: npm run test:unit
      - name: Build Storybook
        run: npm run storybook:build
      - name: Screenshot testing
        run: npm run test:ui:ci